packages:
  - apps/*
  - packages/*

catalog:
  drizzle-orm: ^0.38.3
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ~5.7.3
  vitest: ~3.2.4
  # Pinned to avoid issues with typescript mcp
  zod: ^3.25.76

syncInjectedDepsAfterScripts:
  - build
