title: "[Idea] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Share an idea for Cronicorn!

  - type: textarea
    id: idea
    attributes:
      label: Your idea
      placeholder: What if we could...
    validations:
      required: true
