title: "[Q&A] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Ask away! Check the [docs](https://docs.cronicorn.com) first if you haven't already.

  - type: textarea
    id: question
    attributes:
      label: Your question
      placeholder: How do I...
    validations:
      required: true
