title: "[Show] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Share what you've built with Cronicorn! We love seeing how people use it.

  - type: textarea
    id: showcase
    attributes:
      label: What did you build?
      placeholder: I built... / I'm using Cronicorn to...
    validations:
      required: true
