/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedUsageRouteImport } from './routes/_authed/usage'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedPlanRouteImport } from './routes/_authed/plan'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedApiKeysRouteImport } from './routes/_authed/api-keys'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings.index'
import { Route as AuthedJobsIndexRouteImport } from './routes/_authed/jobs.index'
import { Route as AuthedSettingsConnectedDevicesRouteImport } from './routes/_authed/settings.connected-devices'
import { Route as AuthedRunsIdRouteImport } from './routes/_authed/runs.$id'
import { Route as AuthedJobsNewRouteImport } from './routes/_authed/jobs.new'
import { Route as AuthedJobsIdRouteImport } from './routes/_authed/jobs.$id'
import { Route as AuthedEndpointsIdRouteImport } from './routes/_authed/endpoints.$id'
import { Route as AuthedDeviceApproveRouteImport } from './routes/_authed/device.approve'
import { Route as AuthedJobsIdIndexRouteImport } from './routes/_authed/jobs.$id.index'
import { Route as AuthedEndpointsIdIndexRouteImport } from './routes/_authed/endpoints.$id.index'
import { Route as AuthedJobsIdEndpointsRouteImport } from './routes/_authed/jobs.$id.endpoints'
import { Route as AuthedJobsIdEditRouteImport } from './routes/_authed/jobs.$id.edit'
import { Route as AuthedEndpointsIdRunsRouteImport } from './routes/_authed/endpoints.$id.runs'
import { Route as AuthedEndpointsIdEditRouteImport } from './routes/_authed/endpoints.$id.edit'
import { Route as AuthedJobsJobIdEndpointsNewRouteImport } from './routes/_authed/jobs.$jobId.endpoints.new'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUsageRoute = AuthedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlanRoute = AuthedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApiKeysRoute = AuthedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedJobsIndexRoute = AuthedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsConnectedDevicesRoute =
  AuthedSettingsConnectedDevicesRouteImport.update({
    id: '/connected-devices',
    path: '/connected-devices',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedRunsIdRoute = AuthedRunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsNewRoute = AuthedJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsIdRoute = AuthedJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEndpointsIdRoute = AuthedEndpointsIdRouteImport.update({
  id: '/endpoints/$id',
  path: '/endpoints/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDeviceApproveRoute = AuthedDeviceApproveRouteImport.update({
  id: '/device/approve',
  path: '/device/approve',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsIdIndexRoute = AuthedJobsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedJobsIdRoute,
} as any)
const AuthedEndpointsIdIndexRoute = AuthedEndpointsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedEndpointsIdRoute,
} as any)
const AuthedJobsIdEndpointsRoute = AuthedJobsIdEndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => AuthedJobsIdRoute,
} as any)
const AuthedJobsIdEditRoute = AuthedJobsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthedJobsIdRoute,
} as any)
const AuthedEndpointsIdRunsRoute = AuthedEndpointsIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AuthedEndpointsIdRoute,
} as any)
const AuthedEndpointsIdEditRoute = AuthedEndpointsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthedEndpointsIdRoute,
} as any)
const AuthedJobsJobIdEndpointsNewRoute =
  AuthedJobsJobIdEndpointsNewRouteImport.update({
    id: '/jobs/$jobId/endpoints/new',
    path: '/jobs/$jobId/endpoints/new',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api-keys': typeof AuthedApiKeysRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/plan': typeof AuthedPlanRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/usage': typeof AuthedUsageRoute
  '/device/approve': typeof AuthedDeviceApproveRoute
  '/endpoints/$id': typeof AuthedEndpointsIdRouteWithChildren
  '/jobs/$id': typeof AuthedJobsIdRouteWithChildren
  '/jobs/new': typeof AuthedJobsNewRoute
  '/runs/$id': typeof AuthedRunsIdRoute
  '/settings/connected-devices': typeof AuthedSettingsConnectedDevicesRoute
  '/jobs': typeof AuthedJobsIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/endpoints/$id/edit': typeof AuthedEndpointsIdEditRoute
  '/endpoints/$id/runs': typeof AuthedEndpointsIdRunsRoute
  '/jobs/$id/edit': typeof AuthedJobsIdEditRoute
  '/jobs/$id/endpoints': typeof AuthedJobsIdEndpointsRoute
  '/endpoints/$id/': typeof AuthedEndpointsIdIndexRoute
  '/jobs/$id/': typeof AuthedJobsIdIndexRoute
  '/jobs/$jobId/endpoints/new': typeof AuthedJobsJobIdEndpointsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api-keys': typeof AuthedApiKeysRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/plan': typeof AuthedPlanRoute
  '/usage': typeof AuthedUsageRoute
  '/device/approve': typeof AuthedDeviceApproveRoute
  '/jobs/new': typeof AuthedJobsNewRoute
  '/runs/$id': typeof AuthedRunsIdRoute
  '/settings/connected-devices': typeof AuthedSettingsConnectedDevicesRoute
  '/jobs': typeof AuthedJobsIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/endpoints/$id/edit': typeof AuthedEndpointsIdEditRoute
  '/endpoints/$id/runs': typeof AuthedEndpointsIdRunsRoute
  '/jobs/$id/edit': typeof AuthedJobsIdEditRoute
  '/jobs/$id/endpoints': typeof AuthedJobsIdEndpointsRoute
  '/endpoints/$id': typeof AuthedEndpointsIdIndexRoute
  '/jobs/$id': typeof AuthedJobsIdIndexRoute
  '/jobs/$jobId/endpoints/new': typeof AuthedJobsJobIdEndpointsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authed/api-keys': typeof AuthedApiKeysRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/plan': typeof AuthedPlanRoute
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/_authed/usage': typeof AuthedUsageRoute
  '/_authed/device/approve': typeof AuthedDeviceApproveRoute
  '/_authed/endpoints/$id': typeof AuthedEndpointsIdRouteWithChildren
  '/_authed/jobs/$id': typeof AuthedJobsIdRouteWithChildren
  '/_authed/jobs/new': typeof AuthedJobsNewRoute
  '/_authed/runs/$id': typeof AuthedRunsIdRoute
  '/_authed/settings/connected-devices': typeof AuthedSettingsConnectedDevicesRoute
  '/_authed/jobs/': typeof AuthedJobsIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/endpoints/$id/edit': typeof AuthedEndpointsIdEditRoute
  '/_authed/endpoints/$id/runs': typeof AuthedEndpointsIdRunsRoute
  '/_authed/jobs/$id/edit': typeof AuthedJobsIdEditRoute
  '/_authed/jobs/$id/endpoints': typeof AuthedJobsIdEndpointsRoute
  '/_authed/endpoints/$id/': typeof AuthedEndpointsIdIndexRoute
  '/_authed/jobs/$id/': typeof AuthedJobsIdIndexRoute
  '/_authed/jobs/$jobId/endpoints/new': typeof AuthedJobsJobIdEndpointsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/api-keys'
    | '/dashboard'
    | '/plan'
    | '/settings'
    | '/usage'
    | '/device/approve'
    | '/endpoints/$id'
    | '/jobs/$id'
    | '/jobs/new'
    | '/runs/$id'
    | '/settings/connected-devices'
    | '/jobs'
    | '/settings/'
    | '/endpoints/$id/edit'
    | '/endpoints/$id/runs'
    | '/jobs/$id/edit'
    | '/jobs/$id/endpoints'
    | '/endpoints/$id/'
    | '/jobs/$id/'
    | '/jobs/$jobId/endpoints/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/api-keys'
    | '/dashboard'
    | '/plan'
    | '/usage'
    | '/device/approve'
    | '/jobs/new'
    | '/runs/$id'
    | '/settings/connected-devices'
    | '/jobs'
    | '/settings'
    | '/endpoints/$id/edit'
    | '/endpoints/$id/runs'
    | '/jobs/$id/edit'
    | '/jobs/$id/endpoints'
    | '/endpoints/$id'
    | '/jobs/$id'
    | '/jobs/$jobId/endpoints/new'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/_authed/api-keys'
    | '/_authed/dashboard'
    | '/_authed/plan'
    | '/_authed/settings'
    | '/_authed/usage'
    | '/_authed/device/approve'
    | '/_authed/endpoints/$id'
    | '/_authed/jobs/$id'
    | '/_authed/jobs/new'
    | '/_authed/runs/$id'
    | '/_authed/settings/connected-devices'
    | '/_authed/jobs/'
    | '/_authed/settings/'
    | '/_authed/endpoints/$id/edit'
    | '/_authed/endpoints/$id/runs'
    | '/_authed/jobs/$id/edit'
    | '/_authed/jobs/$id/endpoints'
    | '/_authed/endpoints/$id/'
    | '/_authed/jobs/$id/'
    | '/_authed/jobs/$jobId/endpoints/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/usage': {
      id: '/_authed/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthedUsageRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plan': {
      id: '/_authed/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthedPlanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/api-keys': {
      id: '/_authed/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthedApiKeysRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/jobs/': {
      id: '/_authed/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthedJobsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/connected-devices': {
      id: '/_authed/settings/connected-devices'
      path: '/connected-devices'
      fullPath: '/settings/connected-devices'
      preLoaderRoute: typeof AuthedSettingsConnectedDevicesRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/runs/$id': {
      id: '/_authed/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof AuthedRunsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/new': {
      id: '/_authed/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthedJobsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/$id': {
      id: '/_authed/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthedJobsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/endpoints/$id': {
      id: '/_authed/endpoints/$id'
      path: '/endpoints/$id'
      fullPath: '/endpoints/$id'
      preLoaderRoute: typeof AuthedEndpointsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/device/approve': {
      id: '/_authed/device/approve'
      path: '/device/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof AuthedDeviceApproveRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/$id/': {
      id: '/_authed/jobs/$id/'
      path: '/'
      fullPath: '/jobs/$id/'
      preLoaderRoute: typeof AuthedJobsIdIndexRouteImport
      parentRoute: typeof AuthedJobsIdRoute
    }
    '/_authed/endpoints/$id/': {
      id: '/_authed/endpoints/$id/'
      path: '/'
      fullPath: '/endpoints/$id/'
      preLoaderRoute: typeof AuthedEndpointsIdIndexRouteImport
      parentRoute: typeof AuthedEndpointsIdRoute
    }
    '/_authed/jobs/$id/endpoints': {
      id: '/_authed/jobs/$id/endpoints'
      path: '/endpoints'
      fullPath: '/jobs/$id/endpoints'
      preLoaderRoute: typeof AuthedJobsIdEndpointsRouteImport
      parentRoute: typeof AuthedJobsIdRoute
    }
    '/_authed/jobs/$id/edit': {
      id: '/_authed/jobs/$id/edit'
      path: '/edit'
      fullPath: '/jobs/$id/edit'
      preLoaderRoute: typeof AuthedJobsIdEditRouteImport
      parentRoute: typeof AuthedJobsIdRoute
    }
    '/_authed/endpoints/$id/runs': {
      id: '/_authed/endpoints/$id/runs'
      path: '/runs'
      fullPath: '/endpoints/$id/runs'
      preLoaderRoute: typeof AuthedEndpointsIdRunsRouteImport
      parentRoute: typeof AuthedEndpointsIdRoute
    }
    '/_authed/endpoints/$id/edit': {
      id: '/_authed/endpoints/$id/edit'
      path: '/edit'
      fullPath: '/endpoints/$id/edit'
      preLoaderRoute: typeof AuthedEndpointsIdEditRouteImport
      parentRoute: typeof AuthedEndpointsIdRoute
    }
    '/_authed/jobs/$jobId/endpoints/new': {
      id: '/_authed/jobs/$jobId/endpoints/new'
      path: '/jobs/$jobId/endpoints/new'
      fullPath: '/jobs/$jobId/endpoints/new'
      preLoaderRoute: typeof AuthedJobsJobIdEndpointsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedSettingsRouteChildren {
  AuthedSettingsConnectedDevicesRoute: typeof AuthedSettingsConnectedDevicesRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsConnectedDevicesRoute: AuthedSettingsConnectedDevicesRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedEndpointsIdRouteChildren {
  AuthedEndpointsIdEditRoute: typeof AuthedEndpointsIdEditRoute
  AuthedEndpointsIdRunsRoute: typeof AuthedEndpointsIdRunsRoute
  AuthedEndpointsIdIndexRoute: typeof AuthedEndpointsIdIndexRoute
}

const AuthedEndpointsIdRouteChildren: AuthedEndpointsIdRouteChildren = {
  AuthedEndpointsIdEditRoute: AuthedEndpointsIdEditRoute,
  AuthedEndpointsIdRunsRoute: AuthedEndpointsIdRunsRoute,
  AuthedEndpointsIdIndexRoute: AuthedEndpointsIdIndexRoute,
}

const AuthedEndpointsIdRouteWithChildren =
  AuthedEndpointsIdRoute._addFileChildren(AuthedEndpointsIdRouteChildren)

interface AuthedJobsIdRouteChildren {
  AuthedJobsIdEditRoute: typeof AuthedJobsIdEditRoute
  AuthedJobsIdEndpointsRoute: typeof AuthedJobsIdEndpointsRoute
  AuthedJobsIdIndexRoute: typeof AuthedJobsIdIndexRoute
}

const AuthedJobsIdRouteChildren: AuthedJobsIdRouteChildren = {
  AuthedJobsIdEditRoute: AuthedJobsIdEditRoute,
  AuthedJobsIdEndpointsRoute: AuthedJobsIdEndpointsRoute,
  AuthedJobsIdIndexRoute: AuthedJobsIdIndexRoute,
}

const AuthedJobsIdRouteWithChildren = AuthedJobsIdRoute._addFileChildren(
  AuthedJobsIdRouteChildren,
)

interface AuthedRouteChildren {
  AuthedApiKeysRoute: typeof AuthedApiKeysRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedPlanRoute: typeof AuthedPlanRoute
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedUsageRoute: typeof AuthedUsageRoute
  AuthedDeviceApproveRoute: typeof AuthedDeviceApproveRoute
  AuthedEndpointsIdRoute: typeof AuthedEndpointsIdRouteWithChildren
  AuthedJobsIdRoute: typeof AuthedJobsIdRouteWithChildren
  AuthedJobsNewRoute: typeof AuthedJobsNewRoute
  AuthedRunsIdRoute: typeof AuthedRunsIdRoute
  AuthedJobsIndexRoute: typeof AuthedJobsIndexRoute
  AuthedJobsJobIdEndpointsNewRoute: typeof AuthedJobsJobIdEndpointsNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedApiKeysRoute: AuthedApiKeysRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedPlanRoute: AuthedPlanRoute,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedUsageRoute: AuthedUsageRoute,
  AuthedDeviceApproveRoute: AuthedDeviceApproveRoute,
  AuthedEndpointsIdRoute: AuthedEndpointsIdRouteWithChildren,
  AuthedJobsIdRoute: AuthedJobsIdRouteWithChildren,
  AuthedJobsNewRoute: AuthedJobsNewRoute,
  AuthedRunsIdRoute: AuthedRunsIdRoute,
  AuthedJobsIndexRoute: AuthedJobsIndexRoute,
  AuthedJobsJobIdEndpointsNewRoute: AuthedJobsJobIdEndpointsNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
