name: 🐛 Bug Report
description: Something isn't working as expected
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Share what you can - even a quick note helps.

  - type: textarea
    id: description
    attributes:
      label: What's going on?
      description: Describe the issue and what you expected to happen
      placeholder: |
        When I do X, Y happens, but I expected Z.

        (Optional) Steps to reproduce, error messages, screenshots, etc.
    validations:
      required: true
