name: 💡 Feature Request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make Cronicorn better? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve, or why would this be useful?
      placeholder: I often find myself needing to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
      placeholder: It would be great if...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you tried any workarounds?
    validations:
      required: false
