name: 💡 Feature Request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make Cronicorn better? We'd love to hear it!

  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: Describe your idea and why it would be useful
      placeholder: |
        It would be great if Cronicorn could...

        This would help with...
    validations:
      required: true
