#!/usr/bin/env bash
# =============================================================================
# Cronicorn Quick Setup
# =============================================================================
#
# Downloads docker-compose.yml, generates a .env with secrets, and pulls images.
#
# Usage:
#   bash <(curl -fsSL https://raw.githubusercontent.com/weskerllc/cronicorn/main/scripts/setup.sh)
#
# Or from a cloned repo:
#   bash scripts/setup.sh
#
# Options:
#   --dry-run    Validate prerequisites and show what would be done (no writes)
#
# =============================================================================

set -euo pipefail

# ── Configuration ──────────────────────────────────────────────────────────────

COMPOSE_URL="https://raw.githubusercontent.com/weskerllc/cronicorn/main/docker-compose.yml"
OVERRIDE_URL="https://raw.githubusercontent.com/weskerllc/cronicorn/main/docker-compose.override.yml.example"
MIN_DOCKER_VERSION="24"
MIN_COMPOSE_VERSION="2"
DRY_RUN=false

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
  esac
done

# ── Helpers ────────────────────────────────────────────────────────────────────

info()  { echo "  → $*"; }
ok()    { echo "  ✓ $*"; }
warn()  { echo "  ! $*" >&2; }
fail()  { echo "  ✗ $*" >&2; exit 1; }

# Compare semver major versions: returns 0 if $1 >= $2
# Strips leading non-numeric characters (e.g. "v2.30.0" → "2")
version_gte() {
  local have="${1%%.*}"
  have="${have##*[!0-9]}"
  local need="${2%%.*}"
  [ "$have" -ge "$need" ] 2>/dev/null
}

# ── Prerequisite Checks ───────────────────────────────────────────────────────

echo ""
echo "Cronicorn Setup"
echo "==============="
echo ""

# Docker
if ! command -v docker &>/dev/null; then
  fail "Docker not found. Install Docker Engine 24+: https://docs.docker.com/engine/install/"
fi
DOCKER_VERSION=$(docker version --format '{{.Server.Version}}' 2>/dev/null || echo "0")
if ! version_gte "$DOCKER_VERSION" "$MIN_DOCKER_VERSION"; then
  fail "Docker $DOCKER_VERSION found, but $MIN_DOCKER_VERSION+ is required."
fi
ok "Docker $DOCKER_VERSION"

# Docker Compose
if ! docker compose version &>/dev/null; then
  fail "Docker Compose not found. Install Compose v2+: https://docs.docker.com/compose/install/"
fi
COMPOSE_VERSION=$(docker compose version --short 2>/dev/null || echo "0")
if ! version_gte "$COMPOSE_VERSION" "$MIN_COMPOSE_VERSION"; then
  fail "Docker Compose $COMPOSE_VERSION found, but $MIN_COMPOSE_VERSION+ is required."
fi
ok "Docker Compose $COMPOSE_VERSION"

# openssl (for secret generation)
if ! command -v openssl &>/dev/null; then
  fail "openssl not found. Install openssl to generate secrets."
fi
ok "openssl available"

if [ "$DRY_RUN" = true ]; then
  echo ""
  info "Dry run — no files will be written."
fi

# ── Download Compose File ─────────────────────────────────────────────────────

echo ""

if [ -f "docker-compose.yml" ]; then
  ok "docker-compose.yml already exists (skipped)"
else
  if [ "$DRY_RUN" = true ]; then
    info "Would download docker-compose.yml from $COMPOSE_URL"
  else
    info "Downloading docker-compose.yml..."
    curl -fsSL "$COMPOSE_URL" -o docker-compose.yml
    ok "docker-compose.yml downloaded"
  fi
fi

# ── Download Override Example ─────────────────────────────────────────────────

if [ -f "docker-compose.override.yml.example" ]; then
  ok "docker-compose.override.yml.example already exists (skipped)"
elif [ -f "docker-compose.override.yml" ]; then
  ok "docker-compose.override.yml already exists (skipped example)"
else
  if [ "$DRY_RUN" = true ]; then
    info "Would download docker-compose.override.yml.example"
  else
    info "Downloading docker-compose.override.yml.example..."
    curl -fsSL "$OVERRIDE_URL" -o docker-compose.override.yml.example
    ok "docker-compose.override.yml.example downloaded"
  fi
fi

# ── Generate .env ─────────────────────────────────────────────────────────────

echo ""

if [ -f ".env" ]; then
  ok ".env already exists (not overwriting)"
  # Check if BETTER_AUTH_SECRET looks like a placeholder
  if grep -q "BETTER_AUTH_SECRET=your-" .env 2>/dev/null || grep -q "BETTER_AUTH_SECRET=$" .env 2>/dev/null; then
    warn ".env exists but BETTER_AUTH_SECRET looks unset — edit it before starting."
  fi
else
  if [ "$DRY_RUN" = true ]; then
    info "Would generate .env with BETTER_AUTH_SECRET"
  else
    SECRET=$(openssl rand -base64 32)
    cat > .env <<EOF
# Generated by Cronicorn setup on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# See full configuration options:
# https://github.com/weskerllc/cronicorn/blob/main/.env.example

# Auth secret (auto-generated — do not lose this)
BETTER_AUTH_SECRET=$SECRET

# Uncomment and set for production:
# WEB_URL=https://yourdomain.com
# BETTER_AUTH_URL=https://yourdomain.com
# VITE_API_URL=https://yourdomain.com
# BASE_URL=https://yourdomain.com

# Pin to a specific version for production (default: latest):
# IMAGE_TAG=1.0.0
EOF
    ok ".env generated with secure BETTER_AUTH_SECRET"
  fi
fi

# ── Pull Images ───────────────────────────────────────────────────────────────

echo ""

if [ "$DRY_RUN" = true ]; then
  info "Would run: docker compose pull"
else
  info "Pulling container images (this may take a few minutes)..."
  docker compose pull
  ok "Images pulled"
fi

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo "Setup complete!"
echo ""
if [ "$DRY_RUN" = true ]; then
  echo "  Dry run finished. Re-run without --dry-run to apply."
else
  echo "  Start Cronicorn:"
  echo "    docker compose up -d"
  echo ""
  echo "  Then visit:"
  echo "    API:     http://localhost:3333/api/health"
  echo "    Web app: Expose port 5173 (see docker-compose.override.yml.example)"
  echo ""
  echo "  Default login:"
  echo "    Email:    admin@example.com"
  echo "    Password: devpassword"
  echo ""
  echo "  ⚠  Change these defaults before exposing to the internet."
  echo "  See: https://cronicorn.com/self-hosting/self-hosting-configuration"
fi
echo ""
